import { useCallback, useEffect, useState } from "react"
import { MoreHorizontalIcon, PlusIcon, SearchIcon, XIcon } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog"
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu"
import { Field, FieldDescription, FieldGroup, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Pagination, PaginationContent, PaginationItem, PaginationNext, PaginationPrevious } from "@/components/ui/pagination"
import { CrudTable, type CrudColumn } from "@/components/crud-table"
import { createProject, deleteProject, deleteProjects, listProjects, updateProject, type Project, type ProjectCreate } from "@/lib/api"

const PAGE_SIZE = 10
const formatDate = (value: string) => new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium" }).format(new Date(value))

export function ProjectsPage() {
  const [data, setData] = useState<{ items: Project[]; page: number; page_size: number; total: number }>({ items: [], page: 1, page_size: PAGE_SIZE, total: 0 })
  const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const [debouncedSearch, setDebouncedSearch] = useState(""); const [selected, setSelected] = useState<Set<string>>(new Set()); const [editing, setEditing] = useState<Project | null>(null); const [formOpen, setFormOpen] = useState(false); const [deleting, setDeleting] = useState<Project | null>(null); const [bulkDeleting, setBulkDeleting] = useState(false)
  useEffect(() => { const timeout = window.setTimeout(() => setDebouncedSearch(search.trim()), 300); return () => window.clearTimeout(timeout) }, [search])
  // Search and pagination are controlled state transitions; selection is page-local.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { setPage(1); setSelected(new Set()) }, [debouncedSearch])
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { setSelected(new Set()) }, [page])
  const load = useCallback(async () => { setLoading(true); setError(null); try { setData(await listProjects(page, PAGE_SIZE, debouncedSearch)) } catch (e) { setError(e instanceof Error ? e.message : "Erreur inconnue") } finally { setLoading(false) } }, [page, debouncedSearch])
  // The effect synchronizes the server-backed list whenever the requested page changes.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load() }, [load])
  const columns: CrudColumn<Project>[] = [{ key: "name", header: "Nom", cell: (p) => <span className="font-medium">{p.name}</span> }, { key: "description", header: "Description", cell: (p) => <span className="text-muted-foreground">{p.description || "—"}</span> }, { key: "created_at", header: "Créé le", visibleByDefault: false, cell: (p) => formatDate(p.created_at) }, { key: "updated_at", header: "Modifié le", visibleByDefault: false, cell: (p) => formatDate(p.updated_at) }]
  const totalPages = Math.max(1, Math.ceil(data.total / PAGE_SIZE))
  return <div className="flex flex-col gap-4"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-semibold">Projets</h1><p className="text-sm text-muted-foreground">Gérez vos projets.</p></div><Button onClick={() => { setEditing(null); setFormOpen(true) }}><PlusIcon data-icon="inline-start" />Nouveau projet</Button></div>
    <Card><CardHeader><CardTitle>Liste des projets</CardTitle></CardHeader><CardContent className="flex flex-col gap-4"><CrudTable columnVisibilityKey="projects" rows={data.items} columns={columns} loading={loading} error={error} onRetry={() => void load()} selected={selected} onSelectedChange={(id, checked) => setSelected((old) => { const next = new Set(old); if (checked) next.add(id); else next.delete(id); return next })} onSelectAll={(checked) => setSelected(checked ? new Set(data.items.map((p) => p.id)) : new Set())} toolbar={<div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div className="relative max-w-sm flex-1"><SearchIcon className="absolute top-1/2 left-3 size-4 -translate-y-1/2 text-muted-foreground" /><Input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Rechercher un projet…" className="pl-9" />{search && <Button type="button" variant="ghost" size="icon-sm" className="absolute top-1/2 right-1 -translate-y-1/2" onClick={() => setSearch("")} aria-label="Effacer la recherche"><XIcon /></Button>}</div>{selected.size > 0 && <Button variant="destructive" onClick={() => setBulkDeleting(true)}>Supprimer la sélection ({selected.size})</Button>}</div>} actions={(project) => <DropdownMenu><DropdownMenuTrigger render={<Button variant="ghost" size="icon-sm" aria-label={`Actions pour ${project.name}`} />}><MoreHorizontalIcon /></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={() => { setEditing(project); setFormOpen(true) }}>Modifier</DropdownMenuItem><DropdownMenuItem variant="destructive" onClick={() => setDeleting(project)}>Supprimer</DropdownMenuItem></DropdownMenuContent></DropdownMenu>} />
      <div className="flex items-center justify-between text-sm text-muted-foreground"><span>{data.total} projet{data.total === 1 ? "" : "s"}</span><Pagination className="mx-0 w-auto"><PaginationContent><PaginationItem><PaginationPrevious text="Précédent" href="#" aria-disabled={page <= 1} onClick={(e) => { e.preventDefault(); if (page > 1) setPage(page - 1) }} /></PaginationItem><PaginationItem><span className="px-3">Page {page} / {totalPages}</span></PaginationItem><PaginationItem><PaginationNext text="Suivant" href="#" aria-disabled={page >= totalPages} onClick={(e) => { e.preventDefault(); if (page < totalPages) setPage(page + 1) }} /></PaginationItem></PaginationContent></Pagination></div>
    </CardContent></Card>
    <ProjectFormDialog key={`${formOpen}-${editing?.id ?? "new"}`} open={formOpen} project={editing} onOpenChange={setFormOpen} onSaved={() => void load()} />
    <DeleteDialog project={deleting} onOpenChange={(open) => !open && setDeleting(null)} onDeleted={() => { setDeleting(null); void load() }} />
    <BulkDeleteDialog count={selected.size} open={bulkDeleting} ids={[...selected]} onOpenChange={setBulkDeleting} onDeleted={() => { setBulkDeleting(false); setSelected(new Set()); void load() }} />
  </div>
}

function ProjectFormDialog({ open, project, onOpenChange, onSaved }: { open: boolean; project: Project | null; onOpenChange: (open: boolean) => void; onSaved: () => void }) {
  const [name, setName] = useState(project?.name ?? ""); const [description, setDescription] = useState(project?.description ?? ""); const [error, setError] = useState(""); const [pending, setPending] = useState(false)
  async function submit(e: React.FormEvent) { e.preventDefault(); const trimmed = name.trim(); if (!trimmed) return setError("Le nom est obligatoire."); if (trimmed.length > 255) return setError("Le nom ne peut pas dépasser 255 caractères."); if (description.length > 5000) return setError("La description ne peut pas dépasser 5000 caractères."); setPending(true); setError(""); try { const payload: ProjectCreate = { name: trimmed, description: description || null }; if (project) await updateProject(project.id, payload); else await createProject(payload); onOpenChange(false); onSaved() } catch (e) { setError(e instanceof Error ? e.message : "Erreur inconnue") } finally { setPending(false) } }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>{project ? "Modifier le projet" : "Nouveau projet"}</DialogTitle><DialogDescription>Renseignez les informations du projet.</DialogDescription></DialogHeader><form onSubmit={submit} className="flex flex-col gap-4"><FieldGroup><Field><FieldLabel htmlFor="project-name">Nom</FieldLabel><Input id="project-name" value={name} onChange={(e) => setName(e.target.value)} aria-invalid={Boolean(error && !name.trim())} /></Field><Field><FieldLabel htmlFor="project-description">Description</FieldLabel><Textarea id="project-description" value={description} onChange={(e) => setDescription(e.target.value)} /><FieldDescription>{description.length}/5000 caractères</FieldDescription></Field></FieldGroup>{error && <p className="text-sm text-destructive">{error}</p>}<DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Annuler</Button><Button type="submit" disabled={pending}>{pending ? "Enregistrement…" : "Enregistrer"}</Button></DialogFooter></form></DialogContent></Dialog>
}

function DeleteDialog({ project, onOpenChange, onDeleted }: { project: Project | null; onOpenChange: (open: boolean) => void; onDeleted: () => void }) { const [pending, setPending] = useState(false); const [error, setError] = useState(""); async function remove() { if (!project) return; setPending(true); setError(""); try { await deleteProject(project.id); onDeleted() } catch (e) { setError(e instanceof Error ? e.message : "Erreur inconnue") } finally { setPending(false) } } return <AlertDialog open={Boolean(project)} onOpenChange={onOpenChange}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Supprimer ce projet ?</AlertDialogTitle><AlertDialogDescription>Cette action supprimera définitivement « {project?.name} ».</AlertDialogDescription></AlertDialogHeader>{error && <p className="text-sm text-destructive">{error}</p>}<AlertDialogFooter><AlertDialogCancel disabled={pending}>Annuler</AlertDialogCancel><AlertDialogAction variant="destructive" onClick={remove} disabled={pending}>{pending ? "Suppression…" : "Supprimer"}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog> }

function BulkDeleteDialog({ count, ids, open, onOpenChange, onDeleted }: { count: number; ids: string[]; open: boolean; onOpenChange: (open: boolean) => void; onDeleted: () => void }) { const [pending, setPending] = useState(false); const [error, setError] = useState(""); async function remove() { setPending(true); setError(""); try { await deleteProjects(ids); onDeleted() } catch (e) { setError(e instanceof Error ? e.message : "Erreur inconnue") } finally { setPending(false) } } return <AlertDialog open={open} onOpenChange={onOpenChange}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Supprimer la sélection ?</AlertDialogTitle><AlertDialogDescription>Cette action supprimera définitivement {count} projet{count === 1 ? "" : "s"}.</AlertDialogDescription></AlertDialogHeader>{error && <p className="text-sm text-destructive">{error}</p>}<AlertDialogFooter><AlertDialogCancel disabled={pending}>Annuler</AlertDialogCancel><AlertDialogAction variant="destructive" onClick={remove} disabled={pending}>{pending ? "Suppression…" : "Supprimer"}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog> }
